export const emojiList = {
    "😀" : "Grinning Face : To brighten up a short text. Nice guys use this!",
    "😆" : "Chandler Face : Sarcastic Laugh!",
    "🤣" : "Laughed so hard, that you're crying now too.",
    "😋" : "Specifically : I'm Lovin 'it!",
    "😎" : "Oh Look, I'm a hero with Cool Shades!",
    "😍" : "Eyes with hearts? Believe me, He loves you!",
    "😘" : "Flying Kiss, (Seriosuly? Who prefers that!)",
    "🥰" : "This person is feeling Looooovedd.",
    "🙂" : "Live your last moments, the person is going to kill u.",
    "🤗" : "Never really understood this one!",
    "🤩" : "Yeah Okay, the person likes it.",
    "🤔" : "Just let me think, Dont disturb me!",
    "🤨" : "Dwayne Johnson's Face.Thats it!",
    "😐" : "Seriously? I am offended and you better apologize🙂",
    "😑" : "My decision is made, plz dont try n change it!",
    "😶" : "Smiley equivalent of haww moment in Hindi TV Serials.",
    "🙄" : "The classic Eye roll like Tony Stark's. U better get this refrence🙄",
    "😏" : "Oooo.. Im smirking... Im Vegeta! I smirk a lot.",
    "😮" : "Oohhh So that is what I was missing all this time.",
    "🤐" : "My mouth has been zipped shut. I speak... A LOT.",
    "🥱" : "Feel like insulting a friend? Send this while they are telling their breakup story.",
    "😴" : "Going to sleep! Bye Bye.",
    "😛" : "The face your kid makes, when he has done something mischievous.",
    "😝" : "I'm feeling naughty(NO! Not the bad one)",
    "🤤" : "It's So tasty, that I cant control my saliva!",
    "😒" : "When you roast your friend so much, that he/she doesn't have any Comeback.",
    "😔" : "He is sad, and he wants the world to know it!",
    "🙃" : "No Please don't take me seriously. Im just joking!",
    "🤑" : "Emoji equivalent of - Ab to paisa hi paisa hoga!",
    "🙁" : "Ask him/her : Why is he sad? Close this site & go!!",
    "😟" : "Im worried for you!",
    "😤" : "GOD! IM SO SICK OF YOU! UGHH.",
    "😭" : "Cant... take... it... anymore.. Gotta...Cry.",
    "😨" : "Im shocked... fearfully!",
    "😩" : "He's Ross. He is whiny!",
    "🤯" : "Mind Blown!",
    "😬" : "OOPS Didnt mean that, I wasnt serious! NO NO DONT CRY NOW.",
    "🥵" : "Face After eating chwenchy ke momos!",
    "🥶" : "Its cold outside.",
    "😠" : "Im angry, wait Im gonna turn red.",
    "😡" : "Now Im super-duper MAD!",
    "😷" : "This guy knew about corona, even before China!",
    "🤮" : "Eeeewwww, Lemme puke, not literally though!",
    "🥺" : "Dont fall for the Cat eyes! You are gonna regret it later.",
    "🥳" : "Send this with Happy Birtday wish.",
    "🤫" : "Shhhhhh.. Shhhhh.",
    "🙈" : "I'm blushing!",
    "😂" : "Advice: Use 3-4 together. Just One seems too blunt!",
    "😁" : "Grinning. P.S. Brush your teeth twice, before using this.",
    "😗" : "Kiss Face, But I tend to use it to indirectly tell people the truth.",
    "🥴" : "Want to get out of a conversatin? This works better than hmm.",
    "💩" : "No Ashi*a! Its not Ice-cream! Stop licking it!",
    "😙" : "Cringe - infinity.",
    "🤪" : "The subtle I dont agree with u! OR I'm just crazy!"
};

export const topEmoji = [
    "🤣" , "🥱" , "😂" , "🤤" , "😎"
]